name: Test
on: [ push, pull_request ]
jobs:
  test_linux:
    name: Ubuntu Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [ nightly ]
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - uses: actions/checkout@master
      - name: Run tests
        run: |
          cargo test --all --all-features
