name: 'Upload artifacts'
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  upload_app_image_artifact:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        rust: [nightly]
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Run tests
      run: |
        cargo build --release
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: notes_rs
        path: target/release/notes_rs
